import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { gzipSync } from 'node:zlib';
import { chmodSync, mkdtempSync, mkdirSync, readFileSync, symlinkSync, unlinkSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import test from 'node:test';
import { declaredArtifacts, GH_LINUX_AMD64_BINARY_SHA256, GH_LINUX_AMD64_TARBALL_SHA256, runForTest } from './release-evidence.mjs';
import { loadJson } from './verify-release-manifest.mjs';

const here = dirname(new URL(import.meta.url).pathname);
const baseManifest = loadJson(join(here, '..', 'runic.release.json'));
const baseSchema = join(here, '..', 'runic.release.schema.json');
const sha = (value) => createHash('sha256').update(value).digest('hex');
let testGh;
const run = (argv) => runForTest(argv, testGh);
const clone = () => structuredClone(baseManifest);
const octal = (buffer, offset, size, value) => buffer.write(`${value.toString(8).padStart(size - 1, '0')}\0`, offset, size, 'ascii');
const crc32 = (data) => { let value = 0xffffffff; for (const byte of data) { value ^= byte; for (let bit = 0; bit < 8; bit++) value = (value >>> 1) ^ (value & 1 ? 0xedb88320 : 0); } return (value ^ 0xffffffff) >>> 0; };
function tar(path, contents) { const header = Buffer.alloc(512); header.write(path); octal(header, 100, 8, 0o644); octal(header, 124, 12, contents.length); octal(header, 136, 12, 0); header.fill(0x20, 148, 156); header[156] = 48; header.write('ustar\0', 257); header.write('00', 263); octal(header, 148, 8, header.reduce((sum, byte) => sum + byte, 0)); return Buffer.concat([header, contents, Buffer.alloc((512 - contents.length % 512) % 512), Buffer.alloc(1024)]); }
function tarPrefix(path, prefix, contents) { const value = tar(path, contents); value.write(prefix, 345); value.fill(0x20, 148, 156); octal(value, 148, 8, value.subarray(0, 512).reduce((sum, byte) => sum + byte, 0)); return value; }
function zip(entries) {
  let offset = 0; const locals = []; const centrals = [];
  for (const [name, contents] of entries) { const file = Buffer.from(name); const data = Buffer.from(contents); const crc = crc32(data); const local = Buffer.alloc(30); local.writeUInt32LE(0x04034b50, 0); local.writeUInt16LE(20, 4); local.writeUInt32LE(crc, 14); local.writeUInt32LE(data.length, 18); local.writeUInt32LE(data.length, 22); local.writeUInt16LE(file.length, 26); locals.push(local, file, data); const central = Buffer.alloc(46); central.writeUInt32LE(0x02014b50, 0); central.writeUInt16LE(20, 4); central.writeUInt16LE(20, 6); central.writeUInt32LE(crc, 16); central.writeUInt32LE(data.length, 20); central.writeUInt32LE(data.length, 24); central.writeUInt16LE(file.length, 28); central.writeUInt32LE(offset, 42); centrals.push(central, file); offset += local.length + file.length + data.length; }
  const central = Buffer.concat(centrals); const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(entries.length, 8); end.writeUInt16LE(entries.length, 10); end.writeUInt32LE(central.length, 12); end.writeUInt32LE(offset, 16); return Buffer.concat([...locals, central, end]);
}
function publishedManifest() { const manifest = clone(); for (const item of manifest.compatibilityTrains[0].lanes.find((lane) => lane.name === 'current').versions) item.version = { state: 'published', value: '1.2.3' }; for (const item of manifest.distributions) item.version = { state: 'published', value: '1.2.3' }; return manifest; }
function fixture() {
  const root = mkdtempSync(join(tmpdir(), 'runic-evidence-')); const artifacts = join(root, 'artifacts'); const receipts = join(root, 'receipts'); const bundles = join(root, 'bundles'); const out = join(root, 'out'); const bin = join(root, 'bin'); mkdirSync(artifacts); mkdirSync(receipts); mkdirSync(bundles); mkdirSync(bin);
  const gh = join(bin, 'gh'); writeFileSync(gh, '#!/bin/sh\nif [ "$1" = "--version" ]; then echo "gh version 2.97.0 (test)"; exit 0; fi\n[ "$1" = attestation ] && [ "$2" = verify ] && [ "$4" = --bundle ] && [ -s "$5" ] || exit 2\nd=$(sha256sum "$3" | cut -d" " -f1)\nshift 5\nwhile [ "$1" != --repo ]; do shift; done\nr="https://github.com/$2"\nprintf \'[{"verificationResult":{"statement":{"subject":[{"digest":{"sha256":"%s"}}],"predicate":{"buildDefinition":{"resolvedDependencies":[{"uri":"%s","digest":{"gitCommit":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","gitTree":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"}},{"uri":"https://example.invalid/tool","digest":{"sha256":"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"}}]},"runDetails":{"builder":{"id":"https://example.invalid/builders/1"},"metadata":{"invocationId":"build"}}}}}}]\' "$d" "$r"\n'); chmodSync(gh, 0o755); testGh = gh;
  const manifest = publishedManifest(); const manifestPath = join(root, 'runic.release.json'); writeFileSync(manifestPath, JSON.stringify(manifest));
  const records = declaredArtifacts(manifest); records.forEach((record, index) => { const path = join(artifacts, record.path); mkdirSync(dirname(path), { recursive: true }); if (record.type === 'distribution') writeFileSync(path, zip([['manifest.json', '{}']])); else if (record.ecosystem === 'npm') writeFileSync(path, gzipSync(tar('package/package.json', Buffer.from(JSON.stringify({ name: record.identity, version: record.version, license: 'MIT' }))))); else writeFileSync(path, zip([[record.identity + '.nuspec', `<?xml version="1.0"?><package><metadata><id>${record.identity}</id><version>${record.version}</version></metadata></package>`]])); const data = readFileSync(path); const artifact = { ...record, sha256: sha(data), size: data.length }; const bundlePath = `bundles/${String(index).padStart(2, '0')}.json`; const bundle = join(bundles, bundlePath); mkdirSync(dirname(bundle), { recursive: true }); writeFileSync(bundle, JSON.stringify({ envelope: index })); const repository = manifest.repositories.find((entry) => entry.id === manifest.products.find((entry) => entry.id === record.product).repository).githubRepository; const receipt = { schemaVersion: 1, artifact, attestationBundle: { path: bundlePath, sha256: sha(readFileSync(bundle)) }, source: { repository, revision: 'a'.repeat(40), tree: 'b'.repeat(40) }, builder: { id: 'https://example.invalid/builders/1' }, invocation: { id: 'build' }, materials: [{ uri: 'https://example.invalid/tool', sha256: 'c'.repeat(64) }] }; writeFileSync(join(receipts, `receipt-${String(index).padStart(2, '0')}.json`), JSON.stringify(receipt)); });
  return { root, manifest, manifestPath, artifacts, receipts, bundles, out, gh, records, options: ['--manifest', manifestPath, '--schema', baseSchema, '--artifacts', artifacts, '--receipts', receipts, '--attestation-bundles', bundles, '--out', out, '--lane', 'current', '--created', '2026-08-20T00:00:00Z'] };
}
function refreshReceipt(item, record) { const index = item.records.indexOf(record); const path = join(item.receipts, `receipt-${String(index).padStart(2, '0')}.json`); const receipt = JSON.parse(readFileSync(path)); const bytes = readFileSync(join(item.artifacts, record.path)); receipt.artifact.sha256 = sha(bytes); receipt.artifact.size = bytes.length; writeFileSync(path, JSON.stringify(receipt)); }

test('collects receipt-bound artifacts into deterministic valid SPDX and collection evidence', () => {
  const item = fixture(); run(item.options); const inventory = JSON.parse(readFileSync(join(item.out, 'inventory.json'))); const sbom = JSON.parse(readFileSync(join(item.out, 'sbom.spdx.json'))); const collection = JSON.parse(readFileSync(join(item.out, 'collection.intoto.json')));
  assert.equal(inventory.artifacts.length, item.records.length); assert.equal(sbom.spdxVersion, 'SPDX-2.3'); assert.equal(sbom.creationInfo.created, '2026-08-20T00:00:00Z'); assert.equal(sbom.packages.find((entry) => entry.name.startsWith('npm/'))?.licenseDeclared, 'NOASSERTION'); assert.equal(collection.predicateType, 'https://runic.artifex/release-evidence-collection/v1'); assert.equal(collection.predicate.receipts.length, item.records.length);
  const first = readFileSync(join(item.out, 'bundle.json'), 'utf8'); run([...item.options, '--check']); assert.equal(readFileSync(join(item.out, 'bundle.json'), 'utf8'), first);
});
test('accepts ordinary NuGet metadata names without weakening archive path safety', () => {
  const item = fixture(); const pkg = item.records.find((record) => record.ecosystem === 'nuget'); writeFileSync(join(item.artifacts, pkg.path), zip([['[Content_Types].xml', '<Types/>'], ['_rels/.rels', '<Relationships/>'], ['.signature.p7s', 'signature'], [pkg.identity + '.nuspec', `<package><metadata><id>${pkg.identity}</id><version>${pkg.version}</version></metadata></package>`]])); refreshReceipt(item, pkg);
  assert.doesNotThrow(() => run(item.options));
});
test('keeps the official GitHub CLI archive and extracted-binary pins distinct', () => {
  assert.equal(GH_LINUX_AMD64_TARBALL_SHA256, 'a2c9b8497e1f85b1ad0dfcb78b5a622e098801b8e461e459e88e1ee12f018112');
  assert.equal(GH_LINUX_AMD64_BINARY_SHA256, '141507c337e8b202ad398550c3b73d72f5af92e86f71665214538a81efd4c409');
  assert.notEqual(GH_LINUX_AMD64_TARBALL_SHA256, GH_LINUX_AMD64_BINARY_SHA256);
  assert.match(readFileSync(join(here, '..', '.github/workflows/release-authority.yml'), 'utf8'), new RegExp(GH_LINUX_AMD64_TARBALL_SHA256));
});
test('the CLI ignores environment attempts to inject a fake GitHub CLI', () => {
  const item = fixture(); const result = spawnSync(process.execPath, ['eng/release-evidence.mjs', ...item.options], { cwd: dirname(here), encoding: 'utf8', env: { ...process.env, PATH: `${dirname(item.gh)}:${process.env.PATH}`, NODE_TEST_CONTEXT: 'forged', RUNIC_RELEASE_EVIDENCE_TEST_GH: item.gh } });
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /GitHub CLI binary does not match the approved/);
});
test('rejects a GitHub CLI binary changed after its pinned-path verification', () => {
  const item = fixture(); writeFileSync(item.gh, readFileSync(item.gh, 'utf8').replace('d=$(sha256sum', 'printf \'#!/bin/sh\\nexit 2\\n\' > "$0"\nd=$(sha256sum'));
  assert.throws(() => run(item.options), /GitHub CLI binary changed during evidence collection/);
});
test('fails closed for receipt, artifact, archive, output, and bundle attacks', () => {
  const missingReceipt = fixture(); unlinkSync(join(missingReceipt.receipts, 'receipt-00.json')); assert.throws(() => run(missingReceipt.options), /every declared artifact requires exactly one valid upstream receipt/);
  const badReceipt = fixture(); const path = join(badReceipt.receipts, 'receipt-00.json'); const receipt = JSON.parse(readFileSync(path)); receipt.artifact.sha256 = '0'.repeat(64); writeFileSync(path, JSON.stringify(receipt)); assert.throws(() => run(badReceipt.options), /does not bind exact declared artifact/);
  const badSource = fixture(); const sourcePath = join(badSource.receipts, 'receipt-00.json'); const sourceReceipt = JSON.parse(readFileSync(sourcePath)); sourceReceipt.source.revision = 'not-a-commit'; writeFileSync(sourcePath, JSON.stringify(sourceReceipt)); assert.throws(() => run(badSource.options), /receipt schema validation failed/);
  const extra = fixture(); writeFileSync(join(extra.artifacts, 'extra.bin'), 'no'); assert.throws(() => run(extra.options), /does not exactly match declared artifacts/);
  const linked = fixture(); symlinkSync(join(linked.artifacts, 'nuget'), join(linked.artifacts, 'linked')); assert.throws(() => run(linked.options), /contains a symlink/);
  const missingBundle = fixture(); unlinkSync(join(missingBundle.bundles, 'bundles/00.json')); assert.throws(() => run(missingBundle.options), /does not bind exact bundle/);
  const extraBundle = fixture(); writeFileSync(join(extraBundle.bundles, 'extra.json'), '{}'); assert.throws(() => run(extraBundle.options), /does not exactly match receipt bundle references/);
  const alteredBundle = fixture(); writeFileSync(join(alteredBundle.bundles, 'bundles/00.json'), '{"changed":true}'); assert.throws(() => run(alteredBundle.options), /does not bind exact bundle/);
  const invalidZip = fixture(); const distribution = invalidZip.records.find((record) => record.type === 'distribution'); writeFileSync(join(invalidZip.artifacts, distribution.path), 'not a zip'); refreshReceipt(invalidZip, distribution); assert.throws(() => run(invalidZip.options), /invalid ZIP/);
  const extraNuspec = fixture(); const pkg = extraNuspec.records.find((record) => record.ecosystem === 'nuget'); const altered = zip([[pkg.identity + '.nuspec', `<package><metadata><id>${pkg.identity}</id><version>${pkg.version}</version></metadata></package>`], ['second.nuspec', '<package><metadata><id>x</id><version>1.2.3</version></metadata></package>']]); writeFileSync(join(extraNuspec.artifacts, pkg.path), altered); refreshReceipt(extraNuspec, pkg); assert.throws(() => run(extraNuspec.options), /exactly one nuspec/);
  const traversalZip = fixture(); const zipped = traversalZip.records.find((record) => record.type === 'distribution'); writeFileSync(join(traversalZip.artifacts, zipped.path), zip([['../escape', 'x']])); refreshReceipt(traversalZip, zipped); assert.throws(() => run(traversalZip.options), /invalid ZIP entry path or type/);
  const duplicateZip = fixture(); const duplicate = duplicateZip.records.find((record) => record.type === 'distribution'); writeFileSync(join(duplicateZip.artifacts, duplicate.path), zip([['one', 'x'], ['ONE', 'y']])); refreshReceipt(duplicateZip, duplicate); assert.throws(() => run(duplicateZip.options), /invalid ZIP entry path or type/);
  const duplicateNpm = fixture(); const npm = duplicateNpm.records.find((record) => record.ecosystem === 'npm'); writeFileSync(join(duplicateNpm.artifacts, npm.path), gzipSync(Buffer.concat([tar('package/package.json', Buffer.from(JSON.stringify({ name: npm.identity, version: npm.version }))).subarray(0, -1024), tar('package/package.json', Buffer.from(JSON.stringify({ name: npm.identity, version: npm.version })))]))); refreshReceipt(duplicateNpm, npm); assert.throws(() => run(duplicateNpm.options), /invalid npm tarball|duplicate package/);
  const hiddenAfterEoa = fixture(); const hiddenNpm = hiddenAfterEoa.records.find((record) => record.ecosystem === 'npm'); writeFileSync(join(hiddenAfterEoa.artifacts, hiddenNpm.path), gzipSync(Buffer.concat([tar('package/package.json', Buffer.from(JSON.stringify({ name: hiddenNpm.identity, version: hiddenNpm.version }))), tar('package/package.json', Buffer.from(JSON.stringify({ name: hiddenNpm.identity, version: hiddenNpm.version })))]))); refreshReceipt(hiddenAfterEoa, hiddenNpm); assert.throws(() => run(hiddenAfterEoa.options), /invalid npm tarball/);
  const missingEoa = fixture(); const eoaNpm = missingEoa.records.find((record) => record.ecosystem === 'npm'); const eoaLess = tar('package/package.json', Buffer.from(JSON.stringify({ name: eoaNpm.identity, version: eoaNpm.version }))).subarray(0, -1024); writeFileSync(join(missingEoa.artifacts, eoaNpm.path), gzipSync(eoaLess)); refreshReceipt(missingEoa, eoaNpm); assert.throws(() => run(missingEoa.options), /invalid npm tarball/);
  const traversalNpm = fixture(); const npmTraversal = traversalNpm.records.find((record) => record.ecosystem === 'npm'); writeFileSync(join(traversalNpm.artifacts, npmTraversal.path), gzipSync(tar('../package/package.json', Buffer.from('{}')))); refreshReceipt(traversalNpm, npmTraversal); assert.throws(() => run(traversalNpm.options), /invalid npm tarball/);
  const prefixNpm = fixture(); const npmPrefix = prefixNpm.records.find((record) => record.ecosystem === 'npm'); writeFileSync(join(prefixNpm.artifacts, npmPrefix.path), gzipSync(tarPrefix('package/package.json', '..', Buffer.from(JSON.stringify({ name: npmPrefix.identity, version: npmPrefix.version }))))); refreshReceipt(prefixNpm, npmPrefix); assert.throws(() => run(prefixNpm.options), /invalid npm tarball/);
  const backslashZip = fixture(); const slashRecord = backslashZip.records.find((record) => record.type === 'distribution'); writeFileSync(join(backslashZip.artifacts, slashRecord.path), zip([['..\\escape', 'x']])); refreshReceipt(backslashZip, slashRecord); assert.throws(() => run(backslashZip.options), /invalid ZIP entry path or type/);
  const driveZip = fixture(); const driveRecord = driveZip.records.find((record) => record.type === 'distribution'); writeFileSync(join(driveZip.artifacts, driveRecord.path), zip([['C:/escape', 'x']])); refreshReceipt(driveZip, driveRecord); assert.throws(() => run(driveZip.options), /invalid ZIP entry path or type/);
  const slashCollision = fixture(); const collisionRecord = slashCollision.records.find((record) => record.type === 'distribution'); writeFileSync(join(slashCollision.artifacts, collisionRecord.path), zip([['foo/', ''], ['foo', 'x']])); refreshReceipt(slashCollision, collisionRecord); assert.throws(() => run(slashCollision.options), /invalid ZIP entry path or type/);
  const ancestorCollision = fixture(); const ancestorRecord = ancestorCollision.records.find((record) => record.type === 'distribution'); writeFileSync(join(ancestorCollision.artifacts, ancestorRecord.path), zip([['foo', 'x'], ['foo/bar', 'x']])); refreshReceipt(ancestorCollision, ancestorRecord); assert.throws(() => run(ancestorCollision.options), /invalid ZIP entry path or type/);
  const occupied = fixture(); mkdirSync(occupied.out); writeFileSync(join(occupied.out, 'old'), 'x'); assert.throws(() => run(occupied.options), /newly absent or empty/);
  const emptyDirectory = fixture(); mkdirSync(join(emptyDirectory.receipts, 'empty')); assert.throws(() => run(emptyDirectory.options), /empty or unexpected directories/);
  const caseDirectories = fixture(); mkdirSync(join(caseDirectories.receipts, 'A')); mkdirSync(join(caseDirectories.receipts, 'a')); writeFileSync(join(caseDirectories.receipts, 'A/x.json'), '{}'); writeFileSync(join(caseDirectories.receipts, 'a/y.json'), '{}'); assert.throws(() => run(caseDirectories.options), /case-folded duplicate paths/);
  const outputRace = fixture(); run(outputRace.options); writeFileSync(join(outputRace.out, 'unexpected.json'), '{}'); assert.throws(() => run([...outputRace.options, '--check']), /unexpected files/);
});
test('uses manifest authority only, rejects traversal, duplicate declarations, and unsupported lanes', () => {
  assert.equal(declaredArtifacts(publishedManifest()).some((item) => item.product === 'flow' || /^Runic\.Operations(?:\.ApplicationBridge)?$/i.test(item.identity ?? '')), false);
  const duplicate = publishedManifest(); duplicate.canonicalPackages.push({ ...duplicate.canonicalPackages[0], identity: 'runic.application' }); assert.throws(() => declaredArtifacts(duplicate), /duplicate declared artifact path/);
  const traversal = publishedManifest(); traversal.canonicalPackages[0].identity = '../escape'; assert.throws(() => declaredArtifacts(traversal), /unsafe artifact identity/);
  assert.throws(() => declaredArtifacts(publishedManifest(), 'next-candidate'), /only the current lane is supported/);
});
test('rejects receipt variants, attestation authority/material corruption, and strict release versions', () => {
  const packageShape = fixture(); const packageRecord = packageShape.records.find((record) => record.type === 'package'); const receiptPath = join(packageShape.receipts, `receipt-${String(packageShape.records.indexOf(packageRecord)).padStart(2, '0')}.json`); const receipt = JSON.parse(readFileSync(receiptPath)); receipt.artifact.id = 'not-allowed-on-package'; writeFileSync(receiptPath, JSON.stringify(receipt)); assert.throws(() => run(packageShape.options), /receipt schema validation failed/);
  const distributionShape = fixture(); const distribution = distributionShape.records.find((record) => record.type === 'distribution'); const distributionReceiptPath = join(distributionShape.receipts, `receipt-${String(distributionShape.records.indexOf(distribution)).padStart(2, '0')}.json`); const distributionReceipt = JSON.parse(readFileSync(distributionReceiptPath)); distributionReceipt.artifact.installKind = 'npm-package'; writeFileSync(distributionReceiptPath, JSON.stringify(distributionReceipt)); assert.throws(() => run(distributionShape.options), /receipt schema validation failed/);
  const source = fixture(); const sourcePath = join(source.receipts, 'receipt-00.json'); const sourceReceipt = JSON.parse(readFileSync(sourcePath)); sourceReceipt.source.repository = 'https://github.com/Runic-Artifex/not-the-authority'; writeFileSync(sourcePath, JSON.stringify(sourceReceipt)); assert.throws(() => run(source.options), /not the producing authority/);
  const material = fixture(); writeFileSync(material.gh, readFileSync(material.gh, 'utf8').replace('c'.repeat(64), 'd'.repeat(64))); assert.throws(() => run(material.options), /does not bind digest, source, builder, invocation, and materials/);
  const duplicatedMaterial = fixture(); const duplicateReceiptPath = join(duplicatedMaterial.receipts, 'receipt-00.json'); const duplicateReceipt = JSON.parse(readFileSync(duplicateReceiptPath)); duplicateReceipt.materials.push(structuredClone(duplicateReceipt.materials[0])); writeFileSync(duplicateReceiptPath, JSON.stringify(duplicateReceipt)); assert.throws(() => run(duplicatedMaterial.options), /duplicate materials/);
  const badVersion = publishedManifest(); badVersion.compatibilityTrains[0].lanes.find((lane) => lane.name === 'current').versions[0].version.value = '01.2.3'; assert.throws(() => declaredArtifacts(badVersion), /unassigned or invalid SemVer publication attempt/);
});
